---
title: "Lab4_Demo"
author: "Mateo Robbins"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)     # for data wrangling
library(ggplot2)   # for awesome plotting
library(rsample)   # for data splitting
library(recipes)   # data preprocessing
library(caret)     # for logistic regression modeling
```
Let's explore how employee income and overtime hours worked affect likelihood of employee attrition.  Any predictions?

```{r}
#
data("attrition", package = "modeldata")

df <- attrition %>% mutate_if(is.ordered, factor, ordered = FALSE)

# Create training (70%) and test (30%) sets for the 
# rsample::attrition data.
set.seed(123)  # for reproducibility 
churn_split <- initial_split(df, prop = .7)
churn_train <- training(churn_split)
churn_test  <- testing(churn_split)
```

Let's set up set up our recipes now for preprocessing. 
```{r recipe}
#specify and prep recipe
churn_rec <- recipe(Attrition ~ ., data = churn_train) %>% 
  step_integer(Attrition, zero_based = TRUE) %>% 
  prep(churn_train)

#bake recipe with training data
churn_baked_train <- 
```

```{r specify_models_glm}
#MonthlyIncome
model_inc <- 
  
#OverTime
model_time <- 
```


```{r tidy_model_objs}

```

```{r exp_coefs}
#exponentiate the coefficients from model objects for interpretation. Gives us changes in odds of attrition

```


```{r recode_attrition_test}
churn_baked_test <- 
```

```{r plot_income_attrition}

```

We can add more predictors, creating a multiple logistic regression model

```{r mult_log_regression}
model_both <- 
```
